---
title: "Kaggle House Prices"
author: Javier Guzman Figueira Dominguez
date: Diciembre 2017
output: md_document
---

Inspecci贸nn de los datos
-----------------------

```{r}
# library(pls)
library(ggplot2)

train <- read.csv("train.csv")
test <- read.csv("test.csv")
```

Las dimensiones del conjunto de entrenamiento son las siguientes:

```{r}
dim(train)
dim(test)
```

A continuacin, procedemos a examinar las variables del dataset:

```{r}
str(train)
```

Y observamos el inicio:

```{r}
head(train)
```

Tratamiento de valores perdidos
-------------------------------

```{r}
numeric <- names(train)[which(sapply(train, is.numeric))] # Variables num?ricas

lost_numeric_values_count <- colSums(sapply(train[, numeric], is.na))

plot_Missing <- function(data_in, title = NULL) {
    temp_df <- as.data.frame(ifelse(is.na(data_in), 0, 1))
    temp_df <- temp_df[, order(colSums(temp_df))]
    data_temp <- expand.grid(list(x = 1:nrow(temp_df), y = colnames(temp_df)))
    data_temp$m <- as.vector(as.matrix(temp_df))
    data_temp <- data.frame(x = unlist(data_temp$x), y = unlist(data_temp$y), m = unlist(data_temp$m))
    ggplot2::ggplot(data_temp) +
      ggplot2::geom_tile(ggplot2::aes(x = x, y = y, fill = factor(m))) +
      ggplot2::scale_fill_manual(values = c("white", "black"), name = "Missing\n(0=Yes, 1=No)") +
      ggplot2::theme_light() +
      ggplot2::ylab("") + ggplot2::xlab("") +
      ggplot2::ggtitle(title)
}

plot_Missing(train[, colSums(is.na(train)) > 0])
```

Predicion variable distribution
-------------------------------

```{r}
par(mfrow = c(1, 2))
hist(train$SalePrice, main = "SalePrice")
hist(log10(train$SalePrice), main = "Log10(SalePrice)")

par(mfrow = c(1, 2))
boxplot(train$SalePrice, main = "SalePrice")
boxplot(log10(train$SalePrice), main = "Log10(SalePrice)")
```

Los values (NA) count

```{r}
na_info <- apply(is.na(train), 2, sum)
lost_values_info <- which(na_info > 0)
filtered_lost_values_info <- na_info[lost_values_info]
df_filtered_lost_values_info <- data.frame(filtered_lost_values_info)
# TODO: Change and add a histogram
ggplot() + 
  geom_point(aes(x = rownames(df_filtered_lost_values_info), y = df_filtered_lost_values_info$filtered_lost_values_info)) +
  geom_hline(yintercept = nrow(train)*0.05, color = 'pink') + 
  geom_hline(yintercept = nrow(train)*0.10, color = 'orange') +
  geom_hline(yintercept = nrow(train)*0.20, color = 'blue') + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  xlab('Features with lost values') +
  ylab('Number of lost values')
```

- Distribuci贸n de los valores perdidos en funci贸n de la variable Log10(SalePrice) -

```{r}
for(feature in names(filtered_lost_values_info)) {
  categories <- train[, feature]
  print(ggplot(data = train, aes(x = feature, y = log(SalePrice), fill = categories)) +
        geom_boxplot())
}
```

-Examinamos la distribuci贸n de las variables continuas con respecto a Log10(SalePrice)-
```{r}
numeric_features <- numeric <- names(train)[which(sapply(train, is.numeric))]
numeric_feature_with_lost_values <- intersect(numeric_features, names(filtered_lost_values_info))
for(feature in numeric_feature_with_lost_values) {
  print(qplot(x = train[feature], y = log(train$SalePrice), geom = c("point", "smooth"), method = lm, xlab = feature))
}
```


-LogFrontage-
```{r}

```


```{r}
ggplot(data = train, aes(x = 'Alley', y = log(SalePrice), fill = Alley)) +
        geom_boxplot()
```
